### ISSUE TITLE
[BUG] expectFail is not a valid option for HTTP tests, but there is no error

### ISSUE THREAD

**Issue by terraboops** [grafana/nethax#112]
**Describe the bug**
Currently, setting `expectFail` on an HTTP test results in no error even though it's not a valid option. This is confusing.

**To Reproduce**
Example test plan:
```yaml
testPlan:
  name: "owo"
  description: "uwu
  testTargets:
  - name: "Basic connectivity :3"
    podSelector:
      labels: "name=my-cool-app
      mode: "random"
    tests:
    - name: "EC2 metadata endpoint is blocked"
      endpoint: "http://169.254.169.254/latest/meta-data/"
      statusCode: 401 # Expect failure
      expectFail: true
      timeout: 5s
```

**Expected behavior**
This should produce an error, since `expectFail` isn't applicable to HTTP tests.

**Development Environment (please complete the following information):**
Runner:
- OS: all
- Run in Docker?: N/A
- Kubernetes Version: all
