### ISSUE TITLE
Proposal: extend pod selector capabilities for test targets

### ISSUE THREAD

**Issue by inkel** [grafana/nethax#55]
Currently, [tests targets](https://github.com/grafana/nethax/blob/c92d537e87812a110bac82e48eed931d0161338d/cmd/runner/testplan.go#L26-L32) looks like this:

```yaml
  - name: "basic connectivity tests"
    podSelector: "app.kubernetes.io/instance=opentelemetry-demo"
    podSelection:
      mode: "random"
```

In this definition `podSelector` translates to a label selector when [querying Kubernetes](https://github.com/grafana/nethax/blob/c92d537e87812a110bac82e48eed931d0161338d/cmd/runner/executetest.go#L178-L180).

I propose changing the YAML definition and its Go types to something like the following:

```yaml
  - name: "basic connectivity tests"
    podSelector:
      mode: "random"
      labels: "app.kubernetes.io/instance=opentelemetry-demo"
      fields: "spec.nodeName=example-node-42"
```

With this new, optional, `fields` component we can make use of the field selector in [`metav1.ListOptions`](https://pkg.go.dev/k8s.io/apimachinery@v0.29.2/pkg/apis/meta/v1#ListOptions) and have greater control over the pod selection criteria.

This could be extended further to optionally indicate the container within the pod, addressing the TODO comment [here](https://github.com/grafana/nethax/blob/c92d537e87812a110bac82e48eed931d0161338d/pkg/kubernetes/kubernetes.go#L79-L85).
