### ISSUE TITLE
[FEAT] Define API for executing custom probes

### ISSUE THREAD

**Issue by inkel** [grafana/nethax#96]
**Is your feature request related to a problem? Please describe.**
With #94 we are introducing the possibility of indicating custom probe images in our tests. However, the runner is too coupled with the "official" probe image, and assumes the [command to be run](https://github.com/grafana/nethax/blob/bd75ffa22525cb25d325b870e37ca942a1ec945d/cmd/runner/executetest.go#L118-L131) to have a particular name and expected arguments.

**Describe the solution you'd like**
We should probably add a `command` and `args` fields to `Test` so we can indicate a custom command to be run, eg:

```yaml
    - name: "Check internal service with custom image"
      endpoint: "http://otel-collector.otel-demo.svc.cluster.local:8888/metrics"
      timeout: 3s
      probeImage: "myregistry.io/custom-probe:v1.0.0"
      command: /usr/local/bin/curl
      args:
      - -sSL
      - --data="foo=bar"
      - $endpoint
```

**Describe alternatives you've considered**
Another option would be to just use one `command` field with all the flags defined there.

**Additional context**
We likely also need to make `type` and `statusCode` optional when using custom images, as custom images checks can only inform our runner of their status via the binary exit code.

Ideally this also should be done after #79 is addressed.
